apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: envs-ingress-test-configmap
images:
- name: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/envs-ingress-test
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/version: ""
namePrefix: staging-
namespace: staging
resources:
- ../../base
