apiVersion: apps/v1
kind: Deployment
metadata:
  name: envs-ingress-test
  labels:
    app: envs-ingress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envs-ingress-test
  template:
    spec:
      containers:
      - name: envs-ingress-test
        image: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/envs-ingress-test:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: envs-ingress-test-configmap
    metadata:
      labels:
        app: envs-ingress-test
