apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: envs-ingress-test
configMapGenerator:
- envs:
  - .env
  name: envs-ingress-test-configmap
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
